version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      include: scope
      prefix: "deps"
    rebase-strategy: auto
    open-pull-requests-limit: 5
    reviewers:
      - rgp-paleocapa
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
